/* SQL PROJECT 2.2*/

-- Упражнение 1 - Первые данные
insert into arena (id, name, "size")
values 	(10, 'Палау Блауграна', 8250),
		(20, 'Визинк-Центр - Паласио де Депортес', 15500),
		(30, 'УСК ЦСКА им. А.Я. Гомельского', 5000),
		(40, 'Пис энд Френдшип Стадиум', 12000),
		(50, 'СИБУР Арена', 7140);
	
insert into team (id, city, name, coach_name, arena_id)
values 	(10, 'Барселона', 'Барселона', 'Шарунас Ясикявичюс', 10),
		(20, 'Мадрид', 'Реал Мадрид', 'Пабло Ласо', 20),
		(30, 'Москва', 'ЦСКА', 'Димитрис Итудис', 30),
		(40, 'Пирей', 'Олимпиакос', 'Георгиос Барцокас', 40),
		(50, 'Санкт-Петербург', 'Зенит', 'Хавьер Паскуаль', 50);
	
insert into player (id, name, "position", "height", weight, salary, team_id)
values 	(10, 'Рафа Вильяр', 'защитник', 188, 85, 100000, 
			(select id from team where name = 'Барселона')),
		(20, 'Кайл Курич', 'защитник', 193, 85, 100000, 
			(select id from team where name = 'Барселона')),
		(30, 'Ибу Дьянко Баджи', 'центровой', 211, 103, 200000, 
			(select id from team where name = 'Барселона')),
		(40, 'Ник Калатес', 'разыгрывающий', 198, 97, 150000, 
			(select id from team where name = 'Барселона')),
		(50, 'Никола Миротич', 'форвард', 208, 107, 175000, 
			(select id from team where name = 'Барселона')),
		(60, 'Джейси Кэрролл', 'защитник', 188, 82, 175000, 
			(select id from team where name = 'Реал Мадрид')),
		(70, 'Эли Джон Ндиайе', 'центровой', 203, 110, 275000, 
			(select id from team where name = 'Реал Мадрид')),
		(80, 'Уолтер Тавареш', 'центровой', 220, 120, 273000, 
			(select id from team where name = 'Реал Мадрид')),
		(90, 'Томас Давид Эртель', 'разыгрывающий', 189, 88, 173000, 
			(select id from team where name = 'Реал Мадрид')),
		(100, 'Гершон Ябуселе', 'форвард', 203, 118, 99000, 
			(select id from team where name = 'Реал Мадрид')),
		(110, 'Габриэль Иффе Лундберг', 'защитник', 193, 96, 101000, 
			(select id from team where name = 'ЦСКА')),
		(120, 'Юрий Умрихин', 'защитник', 190, 75, 251000, 
			(select id from team where name = 'ЦСКА')),
		(130, 'Иван Анатольевич Ухов', 'разыгрывающий', 193, 77, 175000, 
			(select id from team where name = 'ЦСКА')),
		(140, 'Александр Хоменко', 'разыгрывающий', 192, 85, 375000, 
			(select id from team where name = 'ЦСКА')),
		(150, 'Андрей Лопатин', 'лёгкий форвард', 208, 92, 205000, 
			(select id from team where name = 'ЦСКА')),
		(160, 'Тайлер Дорси', 'защитник', 193, 83, 205000, 
			(select id from team where name = 'Олимпиакос')),
		(170, 'Яннулис Ларенцакис', 'защитник', 196, 87, 75000, 
			(select id from team where name = 'Олимпиакос')),
		(180, 'Хассан Мартин', 'центровой', 201, 107, 375000, 
			(select id from team where name = 'Олимпиакос')),
		(190, 'Михалис Лунцис', 'разыгрывающий', 195, 90, 475000,
			(select id from team where name = 'Олимпиакос')),
		(200, 'Георгиос Принтезис', 'форвард', 205, 104, 105000, 
			(select id from team where name = 'Олимпиакос')),
		(210, 'Билли Джеймс Бэрон', 'защитник', 188, 88, 75000, 
			(select id from team where name = 'Зенит')),
		(220, 'Артурас Гудайтис', 'центровой', 208, 99, 165000, 
			(select id from team where name = 'Зенит')),
		(230, 'Денис Захаров', 'разыгрывающий', 192, 88, 163000, 
			(select id from team where name = 'Зенит')),
		(240, 'Миндаугас Кузминскас', 'лёгкий форвард', 204, 93, 295000, 
			(select id from team where name = 'Зенит')),
		(250, 'Алекс Пойтресс', 'форвард', 201, 108, 247000, 
			(select id from team where name = 'Зенит'));

-- Упражнение 2 - Оперативные данные
insert into game (id, owner_team_id, guest_team_id, game_date, winner_team_id, owner_score, guest_score, arena_id)
values (10, 
		(select id from team where team.name = 'Барселона'),
		(select id from team where team.name = 'Зенит'),
		'2021-10-22',
		(select id from team where team.name = 'Барселона'),
		84,
		58,
		(select id from arena  where name = 'Палау Блауграна')),
		(20, 
		(select id from team where team.name = 'Барселона'),
		(select id from team where team.name = 'ЦСКА'),
		'2021-11-17',
		(select id from team where team.name = 'Барселона'),
		81,
		73,
		(select id from arena  where name = 'Палау Блауграна')),
		(30, 
		(select id from team where team.name = 'Барселона'),
		(select id from team where team.name = 'Реал Мадрид'),
		'2021-10-12',
		(select id from team where team.name = 'Барселона'),
		93,
		80,
		(select id from arena  where name = 'Палау Блауграна')),
		(40, 
		(select id from team where team.name = 'Барселона'),
		(select id from team where team.name = 'Олимпиакос'),
		'2021-10-15',
		(select id from team where team.name = 'Барселона'),
		83,
		68,
		(select id from arena  where name = 'Палау Блауграна')),
		(50, 
		(select id from team where team.name = 'Зенит'),
		(select id from team where team.name = 'Реал Мадрид'),
		'2022-12-15',
		(select id from team where team.name = 'Реал Мадрид'),
		68,
		75,
		(select id from arena  where name = 'СИБУР Арена')),
		(60, 
		(select id from team where team.name = 'Зенит'),
		(select id from team where team.name = 'ЦСКА'),
		'2022-01-15',
		(select id from team where team.name = 'ЦСКА'),
		67,
		77,
		(select id from arena  where name = 'СИБУР Арена')),
		(70, 
		(select id from team where team.name = 'Зенит'),
		(select id from team where team.name = 'Олимпиакос'),
		'2022-10-20',
		(select id from team where team.name = 'Зенит'),
		84,
		78,
		(select id from arena  where name = 'СИБУР Арена')),
		(80, 
		(select id from team where team.name = 'Реал Мадрид'),
		(select id from team where team.name = 'ЦСКА'),
		'2021-10-28',
		(select id from team where team.name = 'Реал Мадрид'),
		71,
		65,
		(select id from arena  where name = 'Визинк-Центр - Паласио де Депортес')),
		(90, 
		(select id from team where team.name = 'Реал Мадрид'),
		(select id from team where team.name = 'Олимпиакос'),
		'2022-02-01',
		(select id from team where team.name = 'Реал Мадрид'),
		75,
		61,
		(select id from arena  where name = 'Визинк-Центр - Паласио де Депортес')),
		(100, 
		(select id from team where team.name = 'ЦСКА'),
		(select id from team where team.name = 'Олимпиакос'),
		'2022-02-01',
		(select id from team where team.name = 'ЦСКА'),
		79,
		78,
		(select id from arena  where name = 'УСК ЦСКА им. А.Я. Гомельского'));
		
	
-- Упражнение 3 - Первый запрос
select name from arena
where "size" > 9000
order by name asc;

-- Упражнение 4 - Второй запрос
select "name" from player
where "position" in ('защитник', 'форвард')
order by name desc 

-- Упражнение 5 - Третий запрос
select "name" from player 
where height > 215 or weight > 120
order by "name" asc;
